apiVersion: v2
name: helicone-core
description: Helicone Core Application - Web, Jawn, ClickHouse, MinIO, PostgreSQL with AWS Secrets Manager integration
type: application
version: 0.1.0
appVersion: "2025.05.23"
icon: https://helicone.ai/static/logo.png

dependencies:
  - name: ai-gateway
    version: "0.2.0"
    repository: "oci://registry-1.docker.io/helicone"
    condition: helicone.aiGateway.enabled
  - name: postgresql
    version: "12.12.10"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: cloudnative-pg
    version: "1.0.8"
    repository: "https://charts.bitnami.com/bitnami"
    condition: cloudnative-pg.enabled

keywords:
  - helicone
  - llm
  - monitoring
  - observability

maintainers:
  - name: Helicone Team
    email: engineering@helicone.ai

home: https://helicone.ai
sources:
  - https://github.com/Helicone/helicone

annotations:
  # Prerequisites: CloudNativePG operator must be installed in the cluster
  # See CLOUDNATIVEPG_REQUIREMENTS.md for installation instructions
  "helm.sh/prerequisites": |
    CloudNativePG operator must be installed before deploying this chart.
