# Configuration Helicone pour PlateformeIsskar
# Basé sur secrets.example.yaml et adapté pour votre infrastructure

# Désactiver External Secrets (utiliser secrets Kubernetes standards)
externalSecrets:
  enabled: false

helicone:
  # Configuration générale adaptée à votre domaine
  s3:
    serviceAccount:
      enabled: false
    bucketName: "helicone-storage"
    endpoint: "http://helicone-core-minio:9000"

  cloudSqlProxy:
    enabled: false

  migrationRunner:
    image:
      repository: helicone/migrations
      pullPolicy: IfNotPresent
      tag: "v2025.08.20"
    resources: {}

  config:
    # URLs adaptées à isskar-hub.com
    siteUrl: "https://helicone.isskar-hub.com"
    nextPublicAppUrl: "https://helicone.isskar-hub.com"
    jawnPublicUrl: "https://helicone.isskar-hub.com/jawn"
    betterAuthTrustedOrigins: "https://helicone.isskar-hub.com"

    # Configuration base de données PostgreSQL Bitnami
    dbHost: "app-chart-postgresql"
    dbPort: "5432"
    dbName: "helicone"
    dbUser: "helicone"
    heliconePassword: "changeme-in-production"

    # Configuration ClickHouse interne
    clickhouseUrl: "http://helicone-core-clickhouse:8123"
    clickhouseUser: "default"

    # Configuration MinIO interne (stockage local)
    s3BucketName: "helicone-storage"
    s3Endpoint: "http://helicone-core-minio:9000"

    # Configuration environnement
    nodeEnv: "production"
    vercelEnv: "production"
    disableSignup: "false"
    enableEmailSignup: "true"

  # Secrets pour les composants internes
  secrets:
    # Auth secret (généré automatiquement ou fourni)
    betterAuthSecret: "your-secret-key-here"

    # MinIO credentials
    minioRootUser: "admin"
    minioRootPassword: "changeme-in-production"

    # Base de données
    postgresPassword: "changeme-in-production"
    heliconePassword: "changeme-in-production"

    # ClickHouse
    clickhouseUser: "default"

    # Désactiver Stripe (pas nécessaire)
    stripeSecretKey: ""

    # Désactiver S3 externes (utiliser MinIO)
    s3AccessKey: ""
    s3SecretKey: ""

  # Configuration web avec service et ingress
  web:
    enabled: true
    replicaCount: 1
    image:
      repository: helicone/web
      pullPolicy: IfNotPresent
      tag: "v2025.08.20"
    extraEnvVars: []
    router:
      enabled: false
    service:
      type: ClusterIP
      port: 3000
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: helicone.isskar-hub.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - helicone.isskar-hub.com
          secretName: helicone-tls
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 512Mi
    verticalPodAutoscaler:
      enabled: false
    autoscaling:
      enabled: false
    podDisruptionBudget:
      enabled: false

  # Configuration API Jawn
  jawn:
    enabled: true
    replicaCount: 1
    image:
      repository: helicone/jawn
      pullPolicy: IfNotPresent
      tag: "v2025.08.20"
    extraEnvVars: []
    publicUrl: "https://helicone.isskar-hub.com/jawn"
    service:
      type: ClusterIP
      port: 8585
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: helicone.isskar-hub.com
          paths:
            - path: /jawn(/|$)(.*)
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - helicone.isskar-hub.com
          secretName: helicone-tls
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 256Mi
    autoscaling:
      enabled: false

  # Configuration stockage avec des tailles réduites
  clickhouse:
    enabled: true
    image:
      repository: clickhouse/clickhouse-server
      pullPolicy: IfNotPresent
      tag: "23.4.2.11"
    replicaCount: 1
    service:
      type: ClusterIP
      port: 8123
    persistence:
      size: 10Gi
      storageClass: "default"
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "500m"

  minio:
    enabled: true
    image:
      repository: minio/minio
      pullPolicy: IfNotPresent
      tag: "RELEASE.2023-05-18T00-05-36Z"
    replicaCount: 1
    service:
      type: ClusterIP
      port: 9000
      consolePort: 9001
    ingress:
      enabled: false
      ingressClassName: ""
      annotations: {}
    persistence:
      size: 20Gi
      storageClass: "default"
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "512Mi"
        cpu: "200m"
    setup:
      image:
        repository: minio/mc
        tag: "latest"
        pullPolicy: IfNotPresent
      buckets:
        - "helicone-storage"

  cloudnativepg:
    enabled: false

  # Configuration pour créer le secret postgres-credentials avec PostgreSQL Bitnami
  config:
    dbHost: "app-chart-postgresql"
    dbPort: "5432"
    dbName: "helicone"
    dbUser: "helicone"

  aiGateway:
    enabled: false

mailhog:
  enabled: true
  image:
    repository: mailhog/mailhog
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "64Mi"
      cpu: "25m"
    limits:
      memory: "128Mi"
      cpu: "50m"

# Désactiver AI Gateway pour commencer
aiGateway:
  secrets:
    aiGatewayOpenaiApiKey: ""
    aiGatewayAnthropicApiKey: ""
    aiGatewayGeminiApiKey: ""
    aiGatewayHeliconeApiKey: ""

# Configuration PostgreSQL Bitnami
postgresql:
  enabled: true
  image:
    tag: "latest"  # Version PostgreSQL la plus récente
  auth:
    username: helicone
    database: helicone
    enablePostgresUser: true
    existingSecret: my-secretenv
    secretKeys:
      userPasswordKey: helicone-database-password
      adminPasswordKey: helicone-database-password
      postgresPasswordKey: helicone-database-password
  volumePermissions:
    enabled: true
    image:
      tag: latest
  primary:
    initdb:
      userScriptsConfigMap: helicone-init-sql
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    persistence:
      size: 10Gi
      storageClass: "default"
  replicaCount: 1

# Désactiver le sous-chart CloudNativePG
cloudnative-pg:
  enabled: false