# Configuration Helicone pour PlateformeIsskar
# Basé sur secrets.example.yaml et adapté pour votre infrastructure

# Désactiver External Secrets (utiliser secrets Kubernetes standards)
externalSecrets:
  enabled: false

helicone:
  # Configuration générale adaptée à votre domaine
  config:
    # URLs adaptées à isskar-hub.com
    siteUrl: "https://helicone.isskar-hub.com"
    nextPublicAppUrl: "https://helicone.isskar-hub.com"
    jawnPublicUrl: "https://helicone.isskar-hub.com/jawn"
    betterAuthTrustedOrigins: "https://helicone.isskar-hub.com"

    # Configuration base de données interne
    heliconePassword: "changeme-in-production"

    # Configuration ClickHouse interne
    clickhouseUrl: "http://helicone-core-clickhouse:8123"
    clickhouseUser: "default"

    # Configuration MinIO interne (stockage local)
    s3BucketName: "helicone-storage"
    s3Endpoint: "http://helicone-core-minio:9000"

    # Configuration environnement
    nodeEnv: "production"
    vercelEnv: "production"
    disableSignup: "false"
    enableEmailSignup: "true"

  # Secrets pour les composants internes
  secrets:
    # Auth secret (généré automatiquement ou fourni)
    betterAuthSecret: "your-secret-key-here"

    # MinIO credentials
    minioRootUser: "admin"
    minioRootPassword: "changeme-in-production"

    # Base de données
    postgresPassword: "changeme-in-production"
    heliconePassword: "changeme-in-production"

    # ClickHouse
    clickhouseUser: "default"

    # Désactiver Stripe (pas nécessaire)
    stripeSecretKey: ""

    # Désactiver S3 externes (utiliser MinIO)
    s3AccessKey: ""
    s3SecretKey: ""

  # Configuration web avec ingress pour votre domaine
  web:
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: helicone.isskar-hub.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - helicone.isskar-hub.com
          secretName: helicone-tls

  # Configuration API Jawn
  jawn:
    publicUrl: "https://helicone.isskar-hub.com/jawn"
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: helicone.isskar-hub.com
          paths:
            - path: /jawn(/|$)(.*)
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - helicone.isskar-hub.com
          secretName: helicone-tls

  # Configuration stockage avec des tailles adaptées
  clickhouse:
    persistence:
      size: 50Gi
      storageClass: "default"

  minio:
    persistence:
      size: 100Gi
      storageClass: "default"

  cloudnativepg:
    cluster:
      storage:
        size: 20Gi
        storageClass: "default"

# Désactiver AI Gateway pour commencer
aiGateway:
  secrets:
    aiGatewayOpenaiApiKey: ""
    aiGatewayAnthropicApiKey: ""
    aiGatewayGeminiApiKey: ""
    aiGatewayHeliconeApiKey: ""