{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.postgresql.auth.username | b64enc }}
  password: {{ "helicone-database-password" | b64enc }}
{{- end }}