{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.postgresql.auth.username | b64enc }}
  password: {{ (index (lookup "v1" "Secret" .Release.Namespace "my-secretenv").data "helicone-database-password") }}
  url: {{ printf "postgresql://%s:%s@%s:%s/%s" .Values.postgresql.auth.username (index (lookup "v1" "Secret" .Release.Namespace "my-secretenv").data "helicone-database-password" | b64dec) .Values.helicone.config.dbHost .Values.helicone.config.dbPort .Values.helicone.config.dbName | b64enc }}
{{- end }}